name: Deploy Static Portfolio to hanzla.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build static site
      run: npm run build
        
    - name: Deploy to CyberPanel
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "out/*"
        target: "/home/hanzla.com/"
        strip_components: 1
        overwrite: true
        debug: true
        
    - name: Set permissions and cleanup
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Set target directory
          TARGET_DIR="/home/hanzla.com"
          
          # Backup existing files (keep important CyberPanel files)
          if [ -f "$TARGET_DIR/index.html" ]; then
            mv "$TARGET_DIR/index.html" "$TARGET_DIR/index.html.backup.$(date +%Y%m%d_%H%M%S)" || true
          fi
          
          # Clean up old portfolio files (but keep CyberPanel files)
          rm -f "$TARGET_DIR"/*.html 2>/dev/null || true
          rm -rf "$TARGET_DIR/_next" 2>/dev/null || true
          rm -f "$TARGET_DIR/index.txt" 2>/dev/null || true
          
          # Set correct permissions for uploaded files
          find "$TARGET_DIR" -name "*.html" -exec chmod 644 {} \; 2>/dev/null || true
          find "$TARGET_DIR" -name "*.css" -exec chmod 644 {} \; 2>/dev/null || true
          find "$TARGET_DIR" -name "*.js" -exec chmod 644 {} \; 2>/dev/null || true
          find "$TARGET_DIR/_next" -type d -exec chmod 755 {} \; 2>/dev/null || true
          find "$TARGET_DIR/_next" -type f -exec chmod 644 {} \; 2>/dev/null || true
          
          # Create .htaccess for optimization
          tee "$TARGET_DIR/.htaccess" > /dev/null << 'EOF'
          # Enable Gzip compression
          <IfModule mod_deflate.c>
              AddOutputFilterByType DEFLATE text/plain
              AddOutputFilterByType DEFLATE text/html
              AddOutputFilterByType DEFLATE text/xml
              AddOutputFilterByType DEFLATE text/css
              AddOutputFilterByType DEFLATE application/xml
              AddOutputFilterByType DEFLATE application/xhtml+xml
              AddOutputFilterByType DEFLATE application/rss+xml
              AddOutputFilterByType DEFLATE application/javascript
              AddOutputFilterByType DEFLATE application/x-javascript
          </IfModule>

          # Browser caching
          <IfModule mod_expires.c>
              ExpiresActive on
              ExpiresByType text/css "access plus 1 month"
              ExpiresByType application/javascript "access plus 1 month"
              ExpiresByType image/png "access plus 1 month"
              ExpiresByType image/jpg "access plus 1 month"
              ExpiresByType image/jpeg "access plus 1 month"
              ExpiresByType image/webp "access plus 1 month"
              ExpiresByType image/svg+xml "access plus 1 month"
          </IfModule>

          # Security headers
          <IfModule mod_headers.c>
              Header always set X-Content-Type-Options nosniff
              Header always set X-Frame-Options DENY
              Header always set X-XSS-Protection "1; mode=block"
              Header always set Referrer-Policy strict-origin-when-cross-origin
          </IfModule>
          EOF
          
          echo "✅ Static site deployed successfully to hanzla.com!"