name: Deploy Static Portfolio to hanzla.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build static site
      run: npm run build
        
    - name: Deploy to CyberPanel
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "out/*"
        target: "/tmp/portfolio_deploy/"
        strip_components: 1
        overwrite: true
        debug: true
        
    - name: Set permissions and cleanup
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Create temp directory and move files
          mkdir -p /tmp/portfolio_deploy
          
          # Backup current site
          sudo cp -r /home/hanzla.com/public_html /home/hanzla.com/public_html.backup.$(date +%Y%m%d_%H%M%S) || true
          
          # Clear public_html and copy new files
          sudo rm -rf /home/hanzla.com/public_html/*
          sudo cp -r /tmp/portfolio_deploy/* /home/hanzla.com/public_html/
          
          # Set correct permissions
          sudo chown -R hanzla.com:hanzla.com /home/hanzla.com/public_html
          sudo find /home/hanzla.com/public_html -type d -exec chmod 755 {} \;
          sudo find /home/hanzla.com/public_html -type f -exec chmod 644 {} \;
          
          # Cleanup temp directory
          rm -rf /tmp/portfolio_deploy
          
          # Create .htaccess for optimization
          sudo tee /home/hanzla.com/public_html/.htaccess > /dev/null << 'EOF'
          # Enable Gzip compression
          <IfModule mod_deflate.c>
              AddOutputFilterByType DEFLATE text/plain
              AddOutputFilterByType DEFLATE text/html
              AddOutputFilterByType DEFLATE text/xml
              AddOutputFilterByType DEFLATE text/css
              AddOutputFilterByType DEFLATE application/xml
              AddOutputFilterByType DEFLATE application/xhtml+xml
              AddOutputFilterByType DEFLATE application/rss+xml
              AddOutputFilterByType DEFLATE application/javascript
              AddOutputFilterByType DEFLATE application/x-javascript
          </IfModule>

          # Browser caching
          <IfModule mod_expires.c>
              ExpiresActive on
              ExpiresByType text/css "access plus 1 month"
              ExpiresByType application/javascript "access plus 1 month"
              ExpiresByType image/png "access plus 1 month"
              ExpiresByType image/jpg "access plus 1 month"
              ExpiresByType image/jpeg "access plus 1 month"
              ExpiresByType image/webp "access plus 1 month"
              ExpiresByType image/svg+xml "access plus 1 month"
          </IfModule>

          # Security headers
          <IfModule mod_headers.c>
              Header always set X-Content-Type-Options nosniff
              Header always set X-Frame-Options DENY
              Header always set X-XSS-Protection "1; mode=block"
              Header always set Referrer-Policy strict-origin-when-cross-origin
          </IfModule>
          EOF
          
          echo "✅ Static site deployed successfully to hanzla.com!"